-- DEFAULT USER
INSERT INTO T_USERS (ID, USER_ID, USER_NAME) VALUES (1, 'test1', '테스트1');
INSERT INTO T_USERS (ID, USER_ID, USER_NAME) VALUES (2, 'test2', '테스트2');

-- DEFAULT CARDS
INSERT INTO T_CARDS (ID, CARD_NAME, DEFAULT_OP, DEFAULT_DP, COST, CARD_ACT, CARD_EFFECT) VALUES (1, '카드1', 5, 1, 1, 'OPEN', 'TARGET_DMG_1');
INSERT INTO T_CARDS (ID, CARD_NAME, DEFAULT_OP, DEFAULT_DP, COST, CARD_ACT, CARD_EFFECT) VALUES (2, '카드2', 4, 2, 2, 'OPEN', 'TARGET_DMG_2');
INSERT INTO T_CARDS (ID, CARD_NAME, DEFAULT_OP, DEFAULT_DP, COST, CARD_ACT, CARD_EFFECT) VALUES (3, '카드3', 9, 1, 3, 'OPEN', 'TARGET_DMG_3');
INSERT INTO T_CARDS (ID, CARD_NAME, DEFAULT_OP, DEFAULT_DP, COST, CARD_ACT, CARD_EFFECT) VALUES (4, '카드4', 7, 8, 4, 'OPEN', 'TARGET_DMG_4');
INSERT INTO T_CARDS (ID, CARD_NAME, DEFAULT_OP, DEFAULT_DP, COST, CARD_ACT, CARD_EFFECT) VALUES (5, '카드5', 3, 7, 5, 'OPEN', 'DRAW_2');
INSERT INTO T_CARDS (ID, CARD_NAME, DEFAULT_OP, DEFAULT_DP, COST, CARD_ACT, CARD_EFFECT) VALUES (6, '카드6', 2, 6, 6, 'OPEN', 'DRAW_3');
INSERT INTO T_CARDS (ID, CARD_NAME, DEFAULT_OP, DEFAULT_DP, COST, CARD_ACT, CARD_EFFECT) VALUES (7, '카드7', 1, 2, 7, 'OPEN', 'DRAW_1');
INSERT INTO T_CARDS (ID, CARD_NAME, DEFAULT_OP, DEFAULT_DP, COST, CARD_ACT, CARD_EFFECT) VALUES (8, '카드8', 7, 3, 8, 'TURN_END', 'RANDOM_CARD_1');
INSERT INTO T_CARDS (ID, CARD_NAME, DEFAULT_OP, DEFAULT_DP, COST, CARD_ACT, CARD_EFFECT) VALUES (9, '카드9', 1, 2, 9, 'TURN_END', 'RANDOM_CARD_2');
INSERT INTO T_CARDS (ID, CARD_NAME, DEFAULT_OP, DEFAULT_DP, COST, CARD_ACT, CARD_EFFECT) VALUES (10, '카드10', 3, 1, 10, 'TURN_END', 'DRAW_1');
INSERT INTO T_CARDS (ID, CARD_NAME, DEFAULT_OP, DEFAULT_DP, COST, CARD_ACT, CARD_EFFECT) VALUES (11, '카드11', 4, 8, 1, 'TURN_END', 'TARGET_DMG_3');
INSERT INTO T_CARDS (ID, CARD_NAME, DEFAULT_OP, DEFAULT_DP, COST, CARD_ACT, CARD_EFFECT) VALUES (12, '카드12', 6, 3, 1, 'TURN_END', 'TARGET_DMG_1');
INSERT INTO T_CARDS (ID, CARD_NAME, DEFAULT_OP, DEFAULT_DP, COST, CARD_ACT, CARD_EFFECT) VALUES (13, '카드13', 8, 4, 3, 'TURN_END', 'TARGET_DMG_2');
INSERT INTO T_CARDS (ID, CARD_NAME, DEFAULT_OP, DEFAULT_DP, COST, CARD_ACT, CARD_EFFECT) VALUES (14, '카드14', 11, 2, 4, 'TURN_END', 'RANDOM_CARD_1');
INSERT INTO T_CARDS (ID, CARD_NAME, DEFAULT_OP, DEFAULT_DP, COST, CARD_ACT, CARD_EFFECT) VALUES (15, '카드15', 13, 1, 4, 'TURN_END', 'RANDOM_CARD_2');
INSERT INTO T_CARDS (ID, CARD_NAME, DEFAULT_OP, DEFAULT_DP, COST, CARD_ACT, CARD_EFFECT) VALUES (16, '카드16', 1, 14, 3, 'DIE', 'DRAW_1');
INSERT INTO T_CARDS (ID, CARD_NAME, DEFAULT_OP, DEFAULT_DP, COST, CARD_ACT, CARD_EFFECT) VALUES (17, '카드17', 3, 13, 2, 'DIE', 'DRAW_3');
INSERT INTO T_CARDS (ID, CARD_NAME, DEFAULT_OP, DEFAULT_DP, COST, CARD_ACT, CARD_EFFECT) VALUES (18, '카드18', 4, 12, 1, 'DIE', 'TARGET_DMG_3');
INSERT INTO T_CARDS (ID, CARD_NAME, DEFAULT_OP, DEFAULT_DP, COST, CARD_ACT, CARD_EFFECT) VALUES (19, '카드19', 8, 11, 2, 'DIE', 'TARGET_DMG_2');
INSERT INTO T_CARDS (ID, CARD_NAME, DEFAULT_OP, DEFAULT_DP, COST, CARD_ACT, CARD_EFFECT) VALUES (20, '카드20', 6, 10, 4, 'DIE', 'TARGET_DMG_2');
INSERT INTO T_CARDS (ID, CARD_NAME, DEFAULT_OP, DEFAULT_DP, COST, CARD_ACT, CARD_EFFECT) VALUES (21, '카드21', 5, 1, 7, 'DIE', 'RANDOM_CARD_2');
INSERT INTO T_CARDS (ID, CARD_NAME, DEFAULT_OP, DEFAULT_DP, COST, CARD_ACT, CARD_EFFECT) VALUES (22, '카드22', 7, 8, 5, 'DIE', 'RANDOM_CARD_1');
INSERT INTO T_CARDS (ID, CARD_NAME, DEFAULT_OP, DEFAULT_DP, COST, CARD_ACT, CARD_EFFECT) VALUES (23, '카드23', 1, 7, 3, NULL, NULL);
INSERT INTO T_CARDS (ID, CARD_NAME, DEFAULT_OP, DEFAULT_DP, COST, CARD_ACT, CARD_EFFECT) VALUES (24, '카드24', 3, 6, 4, NULL, NULL);
INSERT INTO T_CARDS (ID, CARD_NAME, DEFAULT_OP, DEFAULT_DP, COST, CARD_ACT, CARD_EFFECT) VALUES (25, '카드25', 7, 5, 5, NULL, NULL);
INSERT INTO T_CARDS (ID, CARD_NAME, DEFAULT_OP, DEFAULT_DP, COST, CARD_ACT, CARD_EFFECT) VALUES (26, '카드26', 1, 1, 2, NULL, NULL);
INSERT INTO T_CARDS (ID, CARD_NAME, DEFAULT_OP, DEFAULT_DP, COST, CARD_ACT, CARD_EFFECT) VALUES (27, '카드27', 16, 1, 1, NULL, NULL);
INSERT INTO T_CARDS (ID, CARD_NAME, DEFAULT_OP, DEFAULT_DP, COST, CARD_ACT, CARD_EFFECT) VALUES (28, '카드28', 10, 2, 2, NULL, NULL);
INSERT INTO T_CARDS (ID, CARD_NAME, DEFAULT_OP, DEFAULT_DP, COST, CARD_ACT, CARD_EFFECT) VALUES (29, '카드29', 20, 3, 1, NULL, NULL);
INSERT INTO T_CARDS (ID, CARD_NAME, DEFAULT_OP, DEFAULT_DP, COST, CARD_ACT, CARD_EFFECT) VALUES (30, '카드30', 11, 4, 2, NULL, NULL);